[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "cd frontend && npm ci --legacy-peer-deps",
  "cd ../backend_node && npm ci --legacy-peer-deps"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend_node && npm start"
